import { Link } from 'react-router-dom';
import { CheckCircle2, ClipboardCheck, Database, FileCheck2, RefreshCw, Route, TableProperties, type LucideIcon } from 'lucide-react';
import SEO from '../../components/SEO';
import { toAbsoluteUrl } from '../../lib/site';

const collectionUrl = 'https://shafeeqahfrancis-gif.github.io/portfolio/case-studies/';
const portfolioUrl = 'https://shafeeqahfrancis-gif.github.io/portfolio/';
const deliverables: [string, string, LucideIcon][] = [
  ['Website and workflow QA', 'Defined scenarios, expected results, responsive and keyboard checks, and a traceable issue register.', ClipboardCheck],
  ['Data-quality checks', 'Completeness, duplicate, validity and reconciliation rules using approved or synthetic data.', Database],
  ['SOP documentation', 'Clear ownership, inputs, decisions, escalation points, evidence and completion criteria.', Route],
  ['Release-readiness reviews', 'Links, downloads, placeholders, metadata, packaging and rollback checks before launch.', FileCheck2],
  ['Defect tracking and retesting', 'Priority, reproduction steps, evidence state, owner, target date and retest result.', RefreshCw],
  ['Operational reporting templates', 'Reusable scorecards, action logs, exception reports and proposed measurement plans.', TableProperties],
];

export default function QAOperationsReviewPage() {
  return <>
    <SEO title="QA & Operations Review Service" description="Evidence-led website QA, workflow reviews, data-quality checks, SOP documentation, defect tracking, release readiness and operational reporting from NextGenWebs." path="services/qa-operations-review/" ogImage={toAbsoluteUrl('projects/qa-operations/cover.svg')} ogImageAlt="QA and Operations Review scorecard, checklist and issue register" />
    <main className="mx-auto max-w-7xl px-4 pb-24 pt-32 sm:px-6">
      <nav aria-label="Breadcrumb" className="mb-8 text-sm text-slate-500"><Link to="/" className="hover:text-white">Home</Link><span className="mx-2">/</span><span className="text-slate-300">QA & Operations Review</span></nav>
      <header className="grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end">
        <div><p className="mb-4 text-xs font-bold uppercase tracking-[.22em] text-primary-300">NextGenWebs service</p><h1 className="max-w-4xl text-4xl font-black leading-tight text-white sm:text-6xl">Know what works, what needs attention, and what evidence supports the decision.</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-slate-300">A scoped review for websites, forms, calculators, dashboards, digital products and operating workflows. You receive concrete checks and usable documentation—not a compliance certificate or an unsupported promise that every defect is gone.</p></div>
        <aside className="rounded-3xl border border-amber-400/20 bg-amber-400/10 p-6 text-sm leading-relaxed text-amber-100"><strong className="mb-2 block text-white">Clear boundary</strong> Reviews use approved public pages, local builds and synthetic fixtures. Live enquiries, purchases, customer records and intrusive security testing are excluded unless separately authorised and safely planned.</aside>
      </header>

      <section className="mt-20"><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-primary-300">Concrete deliverables</p><h2 className="mb-8 text-3xl font-bold text-white sm:text-4xl">Choose the review outputs your team can actually use</h2><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{deliverables.map(([title,body,Icon]) => <article key={String(title)} className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><Icon className="mb-5 text-primary-300" size={28}/><h3 className="mb-2 font-bold text-white">{String(title)}</h3><p className="text-sm leading-relaxed text-slate-400">{String(body)}</p></article>)}</div></section>

      <section className="mt-20 grid gap-8 lg:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/[.03] p-7"><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-primary-300">Review process</p><h2 className="mb-6 text-3xl font-bold text-white">A visible chain from scope to retest</h2><ol className="space-y-4">{['Agree the objective, version, evidence boundary and exclusions.','Turn requirements into a weighted scorecard and test cases.','Execute safe checks; label observed, not run and illustrative items separately.','Prioritise issues by impact and propose owners and controls.','Retest fixes and retain a concise release or handoff record.'].map((step,index)=><li key={step} className="flex gap-4 text-sm leading-relaxed text-slate-300"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary-400/15 font-bold text-primary-300">{index+1}</span>{step}</li>)}</ol></div><div className="rounded-3xl border border-white/10 bg-white/[.03] p-7"><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-primary-300">Evidence-led example</p><h2 className="mb-4 text-3xl font-bold text-white">Eight demonstration case studies</h2><p className="mb-5 text-sm leading-relaxed text-slate-300">The companion collection shows scorecards, expected results, actual executed checks, issue-state labels, SOPs and downloadable CSVs across eight industries. Shafeeqah Francis reviewed and approved the existing 18 September 2026 findings, assessments and recommendations. Technical checks remain NextGenWebs/Codex. Code fixes after that date are implemented by NextGenWebs and stay pending her sign-off until an approved pack is recorded. This is demonstration context, not a client engagement, employment result, conversion or revenue claim.</p><div className="flex flex-wrap gap-3"><a href={collectionUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-black hover:bg-slate-200">View the case-study collection</a><a href={portfolioUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-5 py-3 text-sm font-bold text-white hover:bg-white/5">Shafeeqah portfolio</a></div><p className="mt-3 text-xs text-slate-500">Live demonstration collection with attribution and scope boundaries shown on every case.</p></div></section>

      <section className="mt-20"><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-primary-300">What the report distinguishes</p><div className="grid gap-4 md:grid-cols-3">{[['Verified finding','Directly observed in the named version or executed check.'],['Illustrative example','A realistic scenario supplied for planning; not presented as observed.'],['Human-review item','A decision, acceptance check or contribution that still needs an authorised person.']].map(([title,body])=><div key={title} className="rounded-2xl border border-white/10 p-5"><CheckCircle2 className="mb-3 text-emerald-300" size={22}/><h3 className="font-bold text-white">{title}</h3><p className="mt-2 text-sm text-slate-400">{body}</p></div>)}</div></section>

      <section className="mt-20 rounded-3xl border border-primary-400/20 bg-primary-400/10 p-8 text-center"><h2 className="text-3xl font-bold text-white">Need a review with a usable handoff?</h2><p className="mx-auto mt-3 max-w-2xl text-slate-300">Send the page, workflow or release version plus the decision you need to make. I’ll propose a safe scope and concrete deliverables.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link to="/contact" className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-black hover:bg-slate-200">Request a scoped review</Link><Link to="/blog/evidence-led-qa-operations-review/" className="rounded-xl border border-white/15 px-5 py-3 text-sm font-bold text-white hover:bg-white/5">Read the review guide</Link></div></section>
      <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'Service',name:'QA and Operations Review',provider:{'@type':'Organization',name:'NextGenWebs',url:toAbsoluteUrl('')},serviceType:'Website, workflow and data-quality review',url:toAbsoluteUrl('services/qa-operations-review/')})}} />
    </main>
  </>;
}
