import { Link } from 'react-router-dom';

const Section = ({title,children}:{title:string;children:React.ReactNode}) => <section><h2 className="mt-10 border-b border-white/10 pb-2 text-2xl font-bold text-white">{title}</h2>{children}</section>;
const P = ({children}:{children:React.ReactNode}) => <p className="mb-6">{children}</p>;

export default function EvidenceLedQAOperationsReviewContent(){return <div className="prose prose-invert prose-lg max-w-none text-slate-300">
  <p className="mb-6 rounded-2xl border border-amber-400/20 bg-amber-400/10 p-4 text-sm leading-relaxed text-amber-100"><strong>Evidence boundary:</strong> examples are labelled. A source observation is not a live-service result, an automated check is not human work, and a proposed control is not a completed improvement.</p>
  <P>A useful quality review does more than list things that look wrong. It explains what was reviewed, which version was checked, what the expected result was, what actually happened and what still needs a person with authority to decide. That evidence chain is what lets a team reproduce the finding and close it responsibly.</P>
  <Section title="1. Begin with the business decision"><P>Start with the decision the review must support: release this version, accept this data file, improve this handoff, or investigate a recurring failure. A broad request such as “test the website” produces broad notes. A clear objective produces checks that someone can act on.</P><P>Record what is included and excluded. Public pages, local builds and synthetic fixtures are safe defaults. Live submissions, purchases, customer records and intrusive tests need separate authority.</P></Section>
  <Section title="2. Convert requirements into expected results"><P>A test case needs an input or action and an expected result. “Check the calculator” is not enough. “For this approved synthetic configuration, two bedrooms, one bathroom, travel and tax total 111.24” can be repeated and disputed constructively.</P><P>Operational checks work the same way: a handoff is complete only when an owner, next action, due date and evidence are present.</P></Section>
  <Section title="3. Score the reviewed scope, not the whole business"><P>A weighted scorecard makes priorities visible, but it can easily overstate certainty. Score only the criteria examined in the named version. Explain the scale and weighting. Do not turn a source review into a compliance, security, clinical or investment certification.</P></Section>
  <Section title="4. Separate findings, examples and untested risks"><ul className="mb-6 list-disc space-y-2 pl-6"><li><strong className="text-white">Verified finding:</strong> directly observed in retained source or an executed check.</li><li><strong className="text-white">Illustrative example:</strong> a plausible scenario that still needs testing.</li><li><strong className="text-white">Not run:</strong> intentionally outside scope or blocked, with the reason recorded.</li></ul><P>This distinction prevents a planning aid from being repeated later as if it were a real incident.</P></Section>
  <Section title="5. Write issues for retesting"><P>A usable issue includes the reviewed version, reproduction steps, expected and actual results, impact, evidence, priority and proposed owner. Recommendations should describe a control or decision—not promise that conversions will increase or defects will disappear.</P></Section>
  <Section title="6. Turn repeated work into an SOP"><P>An SOP should name inputs, owner, sequence, decision points, escalation, evidence and completion criteria. Keep it short enough to use during real work. If the process changes, update both the SOP and its test cases.</P></Section>
  <Section title="7. Close with human review and a measurement plan"><P>Some work cannot be automated responsibly: approving business rules, checking a physical sign at viewing distance, confirming a customer handoff, or deciding whether evidence is sufficient. Record who made that decision.</P><P>Where results have not been measured, propose a plan: duplicate rate, incomplete-record rate, escaped-defect count, overdue-action count, release rework or support questions. Do not invent a before-and-after result.</P></Section>
  <Section title="See the service and demonstration collection"><P><Link to="/services/qa-operations-review/" className="font-semibold text-primary-300 hover:text-primary-200">NextGenWebs QA & Operations Review</Link> lists the deliverables available for a scoped engagement. The companion demonstration collection shows how scorecards, tests, issue registers and SOPs can be presented while keeping attribution and limitations explicit.</P></Section>
</div>}
