const CASE_STUDY_URL = import.meta.env.BASE_URL + 'projects/qualified-lead-research/';
const ETSY_PLACEHOLDER_URL = 'https://nextgenwebs.etsy.com?placeholder=qualified-lead-research-listing-url';

const sections = [
  { heading: 'Why vague targeting creates poor prospecting', body: ['Most service businesses do not start with a lead problem. They start with a definition problem. When the target market is described as small businesses, coaches, creators or anyone who needs help, the research process has no useful filter. Every company looks possible and every search result can feel like a maybe.', 'That uncertainty affects everything after it. A researcher cannot prioritise, a virtual assistant cannot follow a clear brief, and outreach messages become generic because the fit logic is generic. Poor prospecting often looks like a messaging problem, but the targeting system usually broke first.'] },
  { heading: 'Start by building the Ideal Customer Profile', body: ['A practical Ideal Customer Profile is not a mood board. It should describe the buying context that makes someone worth researching now. Start with the offer, the buyer situation, the decision-maker, the business model, the location or delivery model, and the signals that show a prospect already has the kind of problem your offer solves.', 'For the fictionalised Northstar Growth Studio case, the target moved from community owners to owners of smaller online communities with roughly 100-1,000 members who sell coaching, consulting or professional services and have a visible booking, consultation or application funnel. That is specific enough to guide research without pretending to predict results.'] },
  { heading: 'Write inclusion criteria before searching', body: ['Inclusion criteria are the must-have conditions for deeper research. They might cover industry, company size, community size, owner visibility, commercial intent, location, public professional presence or funnel maturity. The important part is that the criteria are observable from appropriate public sources.', 'A good inclusion rule should help someone decide whether to continue or stop. If the rule is so broad that everything qualifies, it is not a rule. If it requires private data or guesswork, it should be rewritten.'] },
  { heading: 'Give exclusion criteria equal weight', body: ['Most prospecting plans describe who to target. The better ones also describe who to skip. Exclusion criteria protect research time and help keep the system ethical. They also reduce the temptation to chase exciting but poor-fit names.', 'For Northstar-style research, exclusions included celebrity-led communities, prospects with no identifiable owner, communities with no visible business funnel, purely social groups, and records that could not be assessed without private personal information. Disqualification is not negative. It is what makes the ICP usable.'] },
  { heading: 'Verify prospects with public professional signals', body: ['Verification is where a prospect moves from interesting to usable. Owner verification asks whether there is a real operator, founder or decision-maker connected to the business in a public professional context. Funnel verification asks whether the prospect already invites a business conversation through a booking page, application form, work-with-me page or enquiry path.', 'These checks do not require private phone numbers, personal emails or scraped personal databases. The point is to build a responsible public-research framework, not to collect private data.'] },
  { heading: 'Check funnel and buying signals', body: ['Funnel checks help separate active commercial opportunities from interesting audiences. A community with frequent posts but no offer path may be culturally active and still not fit the outreach strategy. A smaller operator with a clear application page, service offer and public founder profile may be more useful for research.', 'Buying signals are not guarantees. They are evidence that the prospect already operates in a way that makes your offer relevant. Examples include service pages, booking calls, cohort applications, hiring signals, partner pages, specialist content or public statements about the problem you solve.'] },
  { heading: 'Use lead scoring to prioritise', body: ['A lead score helps the team stop treating every prospect as equally urgent. A simple weighted model can score size fit, offer relevance, funnel clarity, owner clarity, public information quality and strategic niche fit. The score can be shown as 1-100 or high, medium and low priority bands.', 'The score is not a revenue forecast, close probability or appointment prediction. It is a prioritisation tool. Its job is to make the reason for fit visible so the next action is easier to choose.'] },
  { heading: 'Quality control keeps the system honest', body: ['Quality control is the part many people skip. Before a row is marked ready for outreach prep, check that required fields are complete, exclusions were rechecked, owner and funnel notes point to public sources, the score matches the evidence, duplicates are merged and the notes are clear enough for another person to understand tomorrow.', 'This is how a personal research habit becomes a business process. It also prevents unsupported assumptions from turning into confident but low-quality outreach.'] },
];

export default function HowQualifiedLeadResearchWorksContent() {
  return <div className="prose prose-invert prose-lg max-w-none text-slate-300"><p className="mb-6 rounded-2xl border border-amber-400/20 bg-amber-400/10 p-4 text-sm leading-relaxed text-amber-100">This article explains a prospecting strategy workflow. It does not promise sales, appointments, replies, private contact details or campaign results.</p><p className="mb-6">A vague target market creates vague research. Vague research creates weak outreach. Weak outreach creates silence, which people often misread as proof that outbound does not work. What usually failed first was the targeting system.</p>{sections.map((section) => <section key={section.heading}><h2 className="mt-10 border-b border-white/10 pb-2 text-2xl font-bold text-white">{section.heading}</h2>{section.body.map((paragraph) => <p key={paragraph} className="mb-6">{paragraph}</p>)}</section>)}<h2 className="mt-10 border-b border-white/10 pb-2 text-2xl font-bold text-white">A practical reset you can use today</h2><ol className="mb-8 list-decimal space-y-2 pl-6 text-slate-300"><li>Write what you sell and who has been a strong fit.</li><li>List five inclusion criteria and five exclusions.</li><li>Define owner, decision-maker and funnel-verification checks.</li><li>Choose five research sources and 15 search keywords.</li><li>Create a five-factor scorecard.</li><li>Research 10 prospects and score them honestly.</li></ol><h2 className="mt-10 border-b border-white/10 pb-2 text-2xl font-bold text-white">See the case study and product samples</h2><p className="mb-6">I built a portfolio case study for the <a href={CASE_STUDY_URL} className="font-semibold text-primary-400 hover:text-primary-300">Qualified Lead Research and Prospecting Blueprint</a>. It shows the fictionalised Northstar Growth Studio workflow, sample scoring table, quality-control process and downloadable sample files.</p><p className="mb-6">The Etsy product will be a custom digital package: buyer questionnaire, personalised Ideal Customer Profile, qualification and disqualification rules, public-research source map, scoring model, outreach angle themes, blank workbook and strategy report.</p><p className="mb-6 rounded-2xl border border-primary-400/20 bg-primary-400/10 p-4 text-sm leading-relaxed text-slate-200">Etsy URL placeholder: <a href={ETSY_PLACEHOLDER_URL} target="_blank" rel="noreferrer" className="font-semibold text-primary-300 hover:text-primary-200">Custom Lead Research Prospecting Blueprint</a>. Replace this placeholder after the draft listing is created.</p></div>;
}
