import type { Project } from './types';

/**
 * Portfolio project catalogue. WorkPage, project detail routes, sitemap and
 * related-project links all derive from this list.
 *
 * Etsy: only set `etsyUrl` when the exact public product listing is verified.
 * Draft listings must omit etsyUrl (etsyStatus: 'draft').
 */

export const projects: Project[] = [
  {
    title: 'InsightForge Business Analytics Studio',
    slug: 'insightforge-business-analytics-studio',
    seoTitle: 'InsightForge Business Analytics Studio | Privacy-First CSV Dashboard',
    seoDescription: 'Client-side business analytics studio that turns CSV sales, customer and review data into dashboards, segments, sentiment and reports — no server upload.',
    category: 'Data',
    description: 'A privacy-first business intelligence web application that transforms CSV sales, customer and review data into interactive dashboards, customer segments, sentiment insights, forecasts, scenario plans and downloadable management reports.',
    tags: ['React', 'TypeScript', 'Python', 'Pandas', 'D3', 'Data Visualisation', 'Machine Learning', 'Analytics'],
    liveUrl: 'https://iederees-create.github.io/insightforge-business-analytics-dashboard/',
    // etsyUrl intentionally omitted - the Etsy listing is still a draft
    etsyStatus: 'draft',
    featured: true,
    toolBadge: 'Privacy-First, Fully Client-Side',
    toolHighlight: 'Every calculation — CSV parsing, customer segmentation, sentiment scoring, forecasting and report generation — runs locally in the browser. No sales, customer or review data is ever uploaded to a server.',
    coverImage: `${import.meta.env.BASE_URL}projects/insightforge/cover.webp`,
    previewVideoMp4: `${import.meta.env.BASE_URL}projects/insightforge/preview.mp4`,
    previewVideoWebm: `${import.meta.env.BASE_URL}projects/insightforge/preview.webm`,
    videoPoster: `${import.meta.env.BASE_URL}projects/insightforge/video-poster.webp`,
    mediaAlt: 'InsightForge Business Analytics Studio dashboard showing interactive sales, customer and sentiment charts',
    galleryImages: [
      `${import.meta.env.BASE_URL}projects/insightforge/01-cover.webp`,
      `${import.meta.env.BASE_URL}projects/insightforge/02-dashboard-overview.webp`,
      `${import.meta.env.BASE_URL}projects/insightforge/03-csv-mapping-wizard.webp`,
      `${import.meta.env.BASE_URL}projects/insightforge/04-data-quality-lab.webp`,
      `${import.meta.env.BASE_URL}projects/insightforge/05-sales-product-analytics.webp`,
      `${import.meta.env.BASE_URL}projects/insightforge/06-customer-segmentation.webp`,
      `${import.meta.env.BASE_URL}projects/insightforge/07-sentiment-topic-explorer.webp`,
      `${import.meta.env.BASE_URL}projects/insightforge/08-forecast-scenario-planner.webp`,
      `${import.meta.env.BASE_URL}projects/insightforge/09-report-builder.webp`,
      `${import.meta.env.BASE_URL}projects/insightforge/10-included-credentials.webp`,
    ],
    galleryImageAlts: [
      'InsightForge Business Analytics Studio cover image showing the interactive analytics dashboard and privacy-first CSV workflow',
      'Dashboard overview with interactive sales, revenue and performance charts',
      'CSV column-mapping wizard for importing sales, customer and review data',
      'Data Quality Lab screen highlighting missing values, duplicates and cleaning suggestions',
      'Sales and product analytics view with trend lines and top-product breakdowns',
      'Customer segmentation view showing grouped customer cohorts and segment profiles',
      'Sentiment and topic explorer analysing customer review text for sentiment and recurring themes',
      'Forecast and scenario planner showing projected sales under different business scenarios',
      'Report builder screen for generating a downloadable management report',
      'Included credentials and documentation screen listing what is provided with the analytics studio',
    ],
    features: [
      'Client-only architecture — CSV parsing, analysis and visualisation run entirely in the browser',
      'CSV column-mapping wizard for sales, customer and review data with a data-quality lab',
      'Interactive sales, product and customer analytics dashboards',
      'Automated customer segmentation and cohort profiling',
      'Sentiment and topic analysis on free-text customer reviews',
      'Forecasting and what-if scenario planning tools',
      'One-click downloadable management reports',
      'Optional companion Python/Pandas/scikit-learn toolkit with Jupyter notebooks for deeper offline analysis',
    ],
    caseStudy: {
      methodology: 'Built as a fully client-only, single-page web application — all CSV parsing, analysis and visualisation happen in the visitor\'s own browser. There is no backend server and no database; the app ships as a static bundle (React + TypeScript + Vite) that runs entirely on the user\'s device.',
      toolsUsed: ['React', 'TypeScript', 'Vite', 'Zustand', 'D3', 'Papa Parse', 'Tailwind CSS', 'Python (optional toolkit)', 'Pandas (optional toolkit)', 'scikit-learn (optional toolkit)'],
      technicalChallenge: {
        title: 'Papa Parse worker-thread hang under Vite',
        body: 'During development, Papa Parse\'s worker: true mode silently hung when bundled by Vite\'s ESM-based build — parsing appeared to start but never resolved, with no console error. The issue only surfaced through live browser testing, not unit tests. It was fixed by switching to main-thread chunked parsing, trading a small amount of main-thread work on very large files for reliable, debuggable parsing behaviour.',
      },
      privacyDesign: 'All processing — CSV parsing, segmentation, sentiment analysis, forecasting and report generation — happens locally in the browser. No sales, customer or review data is ever uploaded to a server. The only thing persisted between sessions is the user\'s column-mapping preference, and it is only stored after the user explicitly opts in.',
      testResults: [
        '39 Vitest tests passing across the calculation engine',
        '32 pytest tests passing in the optional Python toolkit',
        'All 5 Jupyter notebooks verified executing cleanly end-to-end',
      ],
    },
  },
  {
    title: 'Bank Desert Analysis Student Lab',
    slug: 'bank-desert-analysis-student-lab',
    articleSlug: 'bank-desert-analysis-python-census-google-places',
    seoTitle: 'Bank Desert Analysis Student Lab | Python & Pandas Financial Access Toolkit',
    seoDescription: 'Python and Pandas learning toolkit for bank desert / financial-access research with maps, statistics lab and privacy-first browser tools.',
    category: 'Data',
    description: 'An academically responsible Python and Pandas learning toolkit that helps students design, analyse and explain financial-access research using demographic data, institution locations, interactive maps and transparent statistical models.',
    tags: ['Python', 'Pandas', 'Jupyter', 'Census API', 'Leaflet', 'Statistics', 'Data Visualisation', 'Geospatial Analysis'],
    liveUrl: 'https://iederees-create.github.io/bank-desert-analysis-student-lab/',
    // etsyUrl intentionally omitted - the Etsy listing is still a draft
    etsyStatus: 'draft',
    featured: true,
    toolBadge: 'Privacy-First, Fully Client-Side',
    toolHighlight: 'A static, client-only single-page app — CSV parsing, the Financial Access Score, and every Statistics Lab calculation run in the student\'s browser. Nothing is sent to a server, because there isn\'t one.',
    coverImage: `${import.meta.env.BASE_URL}projects/bank-desert-analysis/01-cover.png`,
    previewVideoMp4: `${import.meta.env.BASE_URL}projects/bank-desert-analysis/preview.mp4`,
    previewVideoWebm: `${import.meta.env.BASE_URL}projects/bank-desert-analysis/preview.webm`,
    videoPoster: `${import.meta.env.BASE_URL}projects/bank-desert-analysis/video-poster.webp`,
    mediaAlt: 'Bank Desert Analysis Student Lab dashboard showing the Financial Access Score, interactive map, and statistics lab',
    galleryImages: [
      `${import.meta.env.BASE_URL}projects/bank-desert-analysis/01-cover.png`,
      `${import.meta.env.BASE_URL}projects/bank-desert-analysis/05-interactive-map.png`,
      `${import.meta.env.BASE_URL}projects/bank-desert-analysis/06-poverty-access-analysis.png`,
      `${import.meta.env.BASE_URL}projects/bank-desert-analysis/07-statistics-lab.png`,
    ],
    galleryImageAlts: [
      'Bank Desert Analysis Student Lab cover image showing the Financial Access Score dashboard',
      'Interactive Leaflet map showing bank branch locations and area-level financial access scores',
      'Poverty rate versus bank access analysis view with a scatter plot and regression line',
      'Statistics Lab showing descriptive statistics, correlation, regression, and confidence intervals with formulas shown alongside every result',
    ],
    features: [
      'Guided Research Designer that generates a research-question outline, variable list, and project checklist (a template engine, not an AI/LLM call)',
      'Data Source Planner covering Census ACS, FDIC BankFind, NCUA, and optional bring-your-own-key Google Places lookups',
      'Import & Mapping Wizard with independent, toggleable data-cleaning steps (trim, dedupe, missing-value handling, type coercion)',
      'Financial Access Score Builder — a transparent, student-adjustable weighted composite score across six factors, with a sensitivity view',
      'Statistics Lab: descriptive stats, Pearson and Spearman correlation, simple/multiple OLS regression with confidence intervals, residual plots, outlier flags, a multicollinearity check, and a minimum-sample-size guard',
      'Map & Visualisation Lab built on Leaflet with choropleth and scatter-plot views',
      'Report & Citation Builder that assembles findings into an exportable report, entirely client-side',
      'Companion Python analyst-toolkit with ten guided Jupyter notebooks, tested independently with pytest',
    ],
    caseStudy: {
      methodology: 'Built as a static, client-only single-page application (React 19 + TypeScript + Vite) — there is no backend and no database. Every calculation (CSV parsing, the Financial Access Score, and every Statistics Lab method) runs in the student\'s browser. A companion Python package, analyst-toolkit, ships alongside the web app for students who want to go deeper in Jupyter, but it is optional and separate from the web app\'s data flow.',
      toolsUsed: ['React 19', 'TypeScript', 'Vite', 'Tailwind CSS v4', 'Zustand', 'Leaflet', 'react-leaflet', 'D3 (accessible chart primitives)', 'Vitest', 'Testing Library', 'Python', 'Pandas', 'Jupyter', 'pytest'],
      technicalChallenge: {
        title: 'Supporting optional Google Places lookups with zero backend and zero key exposure',
        body: 'The product\'s core constraint is that no student data — and no student credential — should ever leave the browser or touch a server that doesn\'t exist. That made the optional Google Places bring-your-own-key (BYOK) feature in the Data Source Planner a real design problem: it needed to call a paid third-party API without a backend to proxy or store the key. The solution keeps the key in session-only React state (never localStorage), sends it only in direct browser-to-Google requests, and clears it automatically on tab close or refresh — preserving the "nothing leaves your browser except what you explicitly asked to send" guarantee even for the one feature that has to talk to an external paid API.',
      },
      privacyDesign: 'Nothing leaves the browser by default — there is no backend for it to go to. Uploaded CSVs are read via the File API and processed entirely in memory. If a student opts in to Storage Consent, only column-mapping and score-weight preferences are saved to localStorage, never the underlying data. The bundled demonstration dataset is entirely synthetic (fixed random seed, no real Census or institution records). The optional Google Places API key lives only in session-only state and is never persisted or sent anywhere but Google\'s own endpoint.',
      testResults: [
        '107/107 Vitest tests passing across the web app',
        '53/53 pytest tests passing in the analyst-toolkit',
        'All 10 guided Jupyter notebooks execute cleanly end-to-end',
        'Clean production build and lint with zero errors',
      ],
    },
  },
  {
    title: 'RAVERSUS Clinical Portal',
    slug: 'raversus-clinical-portal',
    category: 'Service',
    description: 'Advanced interactive digital clinic and product reservation platform engineered for high-end bioelectric healing technology.',
    tags: ['E-Commerce', 'Custom Animations', 'API Integration'],
    liveUrl: 'https://iederees-create.github.io/raversus-v3/',
    featured: true,
  },
  {
    title: 'Tiling Contractor Website Template',
    slug: 'tiling-contractor-website-template',
    seoTitle: 'Tiling Contractor Website Template | Tile Project Planner',
    seoDescription: 'Lead-generation website template for tiling contractors with an interactive Tile Project Planner, quantity estimates and WhatsApp quote handoff.',
    etsyStatus: 'draft',
    category: 'Service',
    description: 'A premium lead-generation website template for tiling contractors and flooring specialists, featuring an interactive Tile Project Planner, quantity estimator, structured quote summaries, WhatsApp handoff, responsive design and simple business customisation.',
    tags: ['HTML5', 'CSS3', 'JavaScript', 'Responsive Design', 'Local SEO', 'Lead Generation', 'Tile Calculator'],
    liveUrl: 'https://iederees-create.github.io/tableview-tiling-ct-ct/',
    featured: true,
    toolBadge: 'Interactive Tile Project Planner',
    toolHighlight: 'The Tile Project Planner is an original 8-step calculator: visitors enter their room measurements and tile size, choose a layout, and get an instant area/tile/box/cost estimate with indicative material guidance — then send a structured quote request via WhatsApp or email.',
    coverImage: `${import.meta.env.BASE_URL}projects/tableview-tiling/cover.webp`,
    previewVideoMp4: `${import.meta.env.BASE_URL}projects/tableview-tiling/preview.mp4`,
    previewVideoWebm: `${import.meta.env.BASE_URL}projects/tableview-tiling/preview.webm`,
    videoPoster: `${import.meta.env.BASE_URL}projects/tableview-tiling/video-poster.webp`,
    mediaAlt: 'Tiling contractor website template with an interactive Tile Project Planner',
    galleryImages: [
      `${import.meta.env.BASE_URL}projects/tableview-tiling/01-cover.webp`,
      `${import.meta.env.BASE_URL}projects/tableview-tiling/02-desktop.webp`,
      `${import.meta.env.BASE_URL}projects/tableview-tiling/03-mobile.webp`,
      `${import.meta.env.BASE_URL}projects/tableview-tiling/04-planner.webp`,
      `${import.meta.env.BASE_URL}projects/tableview-tiling/05-results.webp`,
      `${import.meta.env.BASE_URL}projects/tableview-tiling/06-quote-whatsapp.webp`,
      `${import.meta.env.BASE_URL}projects/tableview-tiling/07-services-gallery.webp`,
      `${import.meta.env.BASE_URL}projects/tableview-tiling/08-site-config.webp`,
      `${import.meta.env.BASE_URL}projects/tableview-tiling/09-themes.webp`,
      `${import.meta.env.BASE_URL}projects/tableview-tiling/10-included-files.webp`,
    ],
    galleryImageAlts: [
      'Tiling contractor website template cover image showing the interactive tile calculator, responsive design, and digital download',
      'Desktop homepage view of the tiling contractor website template with hero, services grid, and premium architectural design',
      'Mobile homepage and open hamburger navigation menu on the tiling contractor website template',
      'Tile Project Planner interactive tool showing the project-type selection step of the 8-step wizard',
      'Tile Project Planner results step showing measured area, wastage, tile count, box count, and material cost',
      'Tile Project Planner structured quote summary with copy, print, download, and WhatsApp send options',
      'Tiling services grid and project gallery of layout patterns including herringbone and chevron',
      'site-config.js configuration file used to rebrand the tiling website template without editing HTML',
      'Three colour theme presets: Limestone Studio, Charcoal Brass, and Coastal Clay',
      'List of included files, buyer guide, and support documentation in the tiling website template package',
    ],
    features: [
      '8-step Tile Project Planner: type, measurements, tile size, layout, conditions, wastage, estimate, send',
      'Unit conversion (m/cm/ft/in) and single/multiple/wall/floor-plus-wall measurement modes',
      'Instant tile, box, and material-cost estimate — always rounded up, never fractional',
      'Indicative adhesive/grout/levelling/waterproofing guidance, clearly labelled as non-binding',
      'Structured quote summary: copy, print, download, WhatsApp, or email handoff',
      'Three switchable colour themes: Limestone Studio, Charcoal Brass, Coastal Clay',
      'Accessible: keyboard navigation, screen reader support, visible focus states',
      'Zero external dependencies — no CDN fonts, scripts, or tracking',
    ],
  },
{
    title: 'Southern Suburbs Builders Website Template',
    slug: 'southern-suburbs-builders',
    category: 'Service',
    description: 'A construction website template for builders and renovation contractors with an interactive Renovation Scope & Budget Planner that turns vague enquiries into structured quote briefs. Preliminary budget guidance only — not a binding quotation.',
    tags: ['HTML5', 'CSS3', 'JavaScript', 'Responsive Design', 'Local SEO', 'Lead Generation', 'Renovation Planner'],
    liveUrl: 'https://iederees-create.github.io/southern-suburbs-builders-ct/',
    // etsyUrl intentionally omitted — listing not verified as publicly published
    etsyStatus: 'draft',
    featured: true,
    toolBadge: 'Renovation Scope & Budget Planner',
    toolHighlight: 'Interactive planner that helps visitors define project type, measurements, finishes, trades and site conditions, then produces a structured quote summary with preliminary budget range, checklists and WhatsApp/email handoff. Not a binding quotation.',
    coverImage: `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/cover.webp`,
    previewVideoMp4: `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/preview.mp4`,
    previewVideoWebm: `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/preview.webm`,
    videoPoster: `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/video-poster.webp`,
    mediaAlt: 'Southern Suburbs Builders construction website template with Renovation Scope and Budget Planner',
    galleryImages: [
      `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/01-cover.webp`,
      `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/02-desktop.webp`,
      `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/03-mobile.webp`,
      `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/04-planner.webp`,
      `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/05-results.webp`,
      `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/06-budget.webp`,
      `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/07-quote-summary.webp`,
      `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/08-handoff.webp`,
      `${import.meta.env.BASE_URL}projects/southern-suburbs-builders/09-config-themes.webp`,
    ],
    galleryImageAlts: [
      'Cover image for Southern Suburbs Builders construction website template',
      'Desktop homepage of the Southern Suburbs Builders website template',
      'Mobile experience of the Southern Suburbs Builders website template',
      'Renovation Scope and Budget Planner interface',
      'Structured project inputs and scope results in the renovation planner',
      'Preliminary budget range and assumptions with non-binding disclaimer',
      'Structured quote summary from the renovation planner',
      'WhatsApp and email handoff of a structured construction quote brief',
      'Business configuration and theme options for the construction template',
    ],
    features: [
      'Interactive Renovation Scope & Budget Planner for structured construction enquiries',
      'Preliminary project scope, budget range and trade guidance — not a binding quotation',
      'Photo / missing-information checklist intent and site-visit recommendation (as shipped in product)',
      'Structured quote summary with WhatsApp and email handoff',
      'Responsive construction marketing layout',
      'Central business configuration for rebranding',
      'Digital download packaging for Etsy commercialisation (listing may still be draft)',
    ],
    seoTitle: 'Southern Suburbs Builders Website Template | Renovation Scope & Budget Planner',
    seoDescription: 'Construction website template with an interactive Renovation Scope & Budget Planner that turns vague quote enquiries into structured project briefs. Preliminary guidance only.',
    articleSlug: 'construction-website-quote-planner',
    datePublished: '2026-07-13',
    dateModified: '2026-07-13',
    repositoryUrl: 'https://github.com/iederees-create/southern-suburbs-builders-ct',
    projectStatus: 'live-demo',
    buyerAudience: 'Builders, renovation contractors, extension specialists and web designers serving construction clients',
    relatedProjectSlugs: ['tiling-contractor-website-template', 'pest-control-website-template', 'first-choice-construction'],
  },
  {
    title: 'Claude Code Solar Lead Generation Template',
    slug: 'claude-code-solar-lead-generation-template',
    category: 'Service',
    description: 'A responsive solar-installer website template developed with assistance from Claude Code. It includes an interactive savings calculator, lead-capture form, project filtering, configurable business information and mobile-first design.',
    tags: ['Claude Code', 'HTML5', 'CSS3', 'JavaScript', 'GitHub Pages', 'Responsive Design'],
    liveUrl: 'https://iederees-create.github.io/ac-solar-solutions-ct/',
    featured: true,
  },
  {
    title: 'Pest Control Website Template',
    slug: 'pest-control-website-template',
    category: 'Service',
    description: 'A conversion-focused website template for pest-control companies, exterminators and termite specialists, featuring service presentation, quote-request flows, WhatsApp contact, mobile-first design and simple business customisation.',
    tags: ['HTML5', 'CSS3', 'JavaScript', 'Responsive Design', 'Local SEO', 'Lead Generation', 'Pest Control'],
    liveUrl: 'https://iederees-create.github.io/westlake-pest-control-template/',
    featured: true,
  },
  {
    title: 'Vitality Wellness Website Template',
    slug: 'vitality-wellness-website-template',
    category: 'Beauty',
    description: 'A premium React website template for wellness studios, skincare businesses and beauty practitioners, featuring an interactive consultation finder, treatment presentation, booking flows, responsive design and central business customisation.',
    tags: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Responsive Design', 'Local SEO', 'Lead Generation'],
    liveUrl: 'https://iederees-create.github.io/vitality-wellness-claremont-ct/',
    featured: true,
    coverImage: `${import.meta.env.BASE_URL}projects/vitality-wellness/cover.webp`,
    previewVideoMp4: `${import.meta.env.BASE_URL}projects/vitality-wellness/preview.mp4`,
    previewVideoWebm: `${import.meta.env.BASE_URL}projects/vitality-wellness/preview.webm`,
    videoPoster: `${import.meta.env.BASE_URL}projects/vitality-wellness/video-poster.webp`,
    mediaAlt: 'Vitality Wellness website template: sage-and-gold wellness studio homepage with a hero section, consultation finder and treatment pricing cards.',
  },
  {
    title: 'Summit Painting CT',
    slug: 'summit-painting-ct',
    category: 'Service',
    description: 'Premium service business landing page engineered for local visibility, featuring optimized client onboarding paths.',
    tags: ['React', 'Tailwind', 'Vite'],
    liveUrl: 'https://iederees-create.github.io/summit-painting-ct-ct/',
    // etsyUrl removed - see PORTFOLIO-ETSY-LINK-AUDIT.md
    featured: true,
  },
  {
    title: 'Amore Nails CT',
    slug: 'amore-nails-ct',
    category: 'Beauty',
    description: 'Elegant boutique beauty salon application showcasing creative portfolios, service menus, and modern interactive touchpoints.',
    tags: ['TypeScript', 'Tailwind CSS', 'UI/UX'],
    liveUrl: 'https://iederees-create.github.io/amore-nails-ct/',
    // etsyUrl removed - see PORTFOLIO-ETSY-LINK-AUDIT.md
    featured: true,
  },
  {
    title: 'Pixel Perfect Hair',
    slug: 'pixel-perfect-hair',
    category: 'Beauty',
    description: 'Highly visual digital showroom tailored for modern salon styling branding and clean presentation workflows.',
    tags: ['React', 'Vite', 'Responsive Layout'],
    liveUrl: 'https://iederees-create.github.io/pixel-perfect-hair/',
    // etsyUrl removed - see PORTFOLIO-ETSY-LINK-AUDIT.md
  },
  {
    title: 'Zen Skin Studio Website Template',
    slug: 'zen-skin-studio-website-template',
    category: 'Beauty',
    description: 'A premium conversion-focused website template for aesthetic clinics, skincare studios and beauty practitioners, featuring treatment presentation, online enquiry flows, WhatsApp booking, mobile-first design and simple business customisation.',
    tags: ['HTML5', 'CSS3', 'JavaScript', 'Responsive Design', 'Local SEO', 'Beauty Business'],
    liveUrl: 'https://iederees-create.github.io/zen-skin-studio-template/',
    featured: true,
  },
  {
    title: 'Acme Plumbing Claremont',
    slug: 'acme-plumbing-claremont',
    category: 'Service',
    description: 'Conversion-driven emergency dispatch and routing hub optimized for high performance and clean visual hierarchy.',
    tags: ['React', 'SEO Framework', 'Tailwind'],
    liveUrl: 'https://iederees-create.github.io/acme-plumbing-claremont-ct/',
    // etsyUrl removed - see PORTFOLIO-ETSY-LINK-AUDIT.md
  },
  {
    title: 'Window Wizards CT',
    slug: 'window-wizards-ct',
    category: 'Service',
    description: 'Polished commercial service application focusing on interactive quotes and premium glass components.',
    tags: ['TypeScript', 'Vite', 'Components'],
    liveUrl: 'https://iederees-create.github.io/window-wizards-ct-ct/',
    // etsyUrl removed - see PORTFOLIO-ETSY-LINK-AUDIT.md
  },
  {
    title: 'First Choice Construction',
    slug: 'first-choice-construction',
    category: 'Service',
    description: 'Heavyweight construction enterprise portal designed to showcase multi-stage real estate developments and scale.',
    tags: ['React', 'Production Build', 'Tailwind'],
    liveUrl: 'https://iederees-create.github.io/first-choice-construction-ct/',
    // etsyUrl removed - see PORTFOLIO-ETSY-LINK-AUDIT.md
    featured: true,
  },
  {
    title: 'Creator Hub Pro Template',
    slug: 'creator-hub-pro-template',
    category: 'Creative',
    description: 'A modular, backend-ready portfolio ecosystem designed for high-tier digital creators to manage brand partnerships and media grids.',
    tags: ['Component Driven', 'Supabase Ready', 'Responsive UI'],
    liveUrl: 'https://iederees-create.github.io/creator-hub-template/',
    // etsyUrl removed - see PORTFOLIO-ETSY-LINK-AUDIT.md
    featured: true,
  },
  {
    title: 'Aura Signs',
    slug: 'aura-signs',
    category: 'Creative',
    description: 'Stunning artistic branding workspace focused on visual design aesthetics, layout assets, and sign production.',
    tags: ['UI/UX Design', 'Vite', 'Tailwind'],
    liveUrl: 'https://iederees-create.github.io/aura-signs/',
    // etsyUrl removed - see PORTFOLIO-ETSY-LINK-AUDIT.md
  },
  {
    title: 'Fluent Path Tutoring',
    slug: 'fluent-path-tutoring',
    articleSlug: 'why-educational-businesses-need-custom-learning-hubs',
    seoTitle: 'Fluent Path Tutoring | Custom Learning Hub Template',
    seoDescription: 'Learning management style tutoring site designed for modern educational businesses.',
    category: 'Education',
    description: 'Clean learning management index and appointment hub designed for modern educational structures and smooth navigation.',
    tags: ['TypeScript', 'React', 'Data Visuals'],
    liveUrl: 'https://iederees-create.github.io/fluent-path-tutoring/',
    // etsyUrl removed - see PORTFOLIO-ETSY-LINK-AUDIT.md
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getRelatedProjects(project: Project): Project[] {
  return (project.relatedProjectSlugs ?? [])
    .map((s) => getProjectBySlug(s))
    .filter((p): p is Project => Boolean(p));
}

export const projectCategories = ['All', 'Service', 'Beauty', 'Education', 'Creative', 'Data'] as const;
